
- name: "extract artifact"
  unarchive:
    src: artifact.tar.gz
    dest: ~

- name: "startup node"
  shell: |
    cd ~/backend/dist
    #npm install
    pm2 stop default
    pm2 start npm -- start
    