
- name: "unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/

- name: "executing node"
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start npm -- start
    pm2 ls
  